### ISSUE TITLE
Quickstart config fails to validate

### ISSUE THREAD

**Issue by octfx** [cupcakearmy/autorestic#62]
Using the config provided in the [Quickstart docs](https://autorestic.vercel.app/quick), running `autorestic check` results in:

```
Using config file: /root/.autorestic.yml
panic: 4 error(s) decoding:

* 'Backends[0][key]' expected a map, got 'string'
* 'Backends[0][name]' expected a map, got 'string'
* 'Backends[0][path]' expected a map, got 'string'
* 'Backends[0][type]' expected a map, got 'string'

goroutine 1 [running]:
github.com/cupcakearmy/autorestic/internal.GetConfig.func1()
        /home/runner/work/autorestic/autorestic/internal/config.go:39 +0x15f
sync.(*Once).doSlow(0xbbc128, 0x8dcf70)
        /opt/hostedtoolcache/go/1.16.3/x64/src/sync/once.go:68 +0xec
sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.16.3/x64/src/sync/once.go:59
github.com/cupcakearmy/autorestic/internal.GetConfig(0xc0001426c0)
        /home/runner/work/autorestic/autorestic/internal/config.go:30 +0x65
github.com/cupcakearmy/autorestic/cmd.initConfig()
        /home/runner/work/autorestic/autorestic/cmd/root.go:60 +0xaa
github.com/spf13/cobra.(*Command).preRun(0xb83060)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:882 +0x49
github.com/spf13/cobra.(*Command).execute(0xb83060, 0xbbc088, 0x0, 0x0, 0xb83060, 0xbbc088)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:818 +0x14f
github.com/spf13/cobra.(*Command).ExecuteC(0xb832e0, 0xb44278, 0x948f10, 0x93bbc8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cupcakearmy/autorestic/cmd.Execute()
        /home/runner/work/autorestic/autorestic/cmd/root.go:33 +0x2d
main.main()
        /home/runner/work/autorestic/autorestic/main.go:41 +0x2a

```

I'm using the latest autorestic release on a debian 10 machine.

**Comment by cupcakearmy** [comment]
I messed up, I was trying an alternative config format. I'll fix it today. Backends should should not be an array but map, like the locations.
Thanks for reporting!

**Comment by cupcakearmy** [comment]
Fixed :)
